// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getHeaderInfo: () => __TAURI_INVOKE<HeaderInfo>("get_header_info"),
	getDpsPlayerWindow: () => __TAURI_INVOKE<PlayersWindow>("get_dps_player_window"),
	getDpsSkillWindow: (playerUidStr: string) => typedError<SkillsWindow, string>(__TAURI_INVOKE("get_dps_skill_window", { playerUidStr })),
	getDpsBossOnlyPlayerWindow: () => __TAURI_INVOKE<PlayersWindow>("get_dps_boss_only_player_window"),
	getDpsBossOnlySkillWindow: (playerUidStr: string) => typedError<SkillsWindow, string>(__TAURI_INVOKE("get_dps_boss_only_skill_window", { playerUidStr })),
	getHealPlayerWindow: () => __TAURI_INVOKE<PlayersWindow>("get_heal_player_window"),
	getHealSkillWindow: (playerUidStr: string) => typedError<SkillsWindow, string>(__TAURI_INVOKE("get_heal_skill_window", { playerUidStr })),
	resetEncounter: () => __TAURI_INVOKE<void>("reset_encounter"),
	togglePauseEncounter: () => __TAURI_INVOKE<void>("toggle_pause_encounter"),
	hardReset: () => __TAURI_INVOKE<void>("hard_reset"),
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	getTestPlayerWindow: () => __TAURI_INVOKE<PlayersWindow>("get_test_player_window"),
	getTestSkillWindow: (playerUid: string) => typedError<SkillsWindow, string>(__TAURI_INVOKE("get_test_skill_window", { playerUid })),
	setBptimerEnabled: (enabled: boolean) => __TAURI_INVOKE<void>("set_bptimer_enabled", { enabled }),
	extractModulesFromLocalPlayer: () => typedError<ModuleOptimizerExportResult, string>(__TAURI_INVOKE("extract_modules_from_local_player")),
};

/* Types */
export type HeaderInfo = {
	totalDps: number | null,
	totalDmg: number | null,
	elapsedMs: number | null,
	timeLastCombatPacketMs: number | null,
};

export type ModuleOptimizerExportResult = {
	url: string,
	exported_path: string | null,
};

export type PlayerRow = {
	uid: number | null,
	abilityScore: number | null,
	className: string,
	classSpecName: string,
	name: string,
	totalValue: number | null,
	valuePerSec: number | null,
	valuePct: number | null,
	critRate: number | null,
	critValueRate: number | null,
	luckyRate: number | null,
	luckyValueRate: number | null,
	hits: number | null,
	hitsPerMinute: number | null,
};

export type PlayersWindow = {
	playerRows: PlayerRow[],
	localPlayerUid: number | null,
	topValue: number | null,
};

export type SkillRow = {
	uid: number | null,
	name: string,
	totalValue: number | null,
	valuePerSec: number | null,
	valuePct: number | null,
	critRate: number | null,
	critValueRate: number | null,
	luckyRate: number | null,
	luckyValueRate: number | null,
	hits: number | null,
	hitsPerMinute: number | null,
};

export type SkillsWindow = {
	inspectedPlayer: PlayerRow,
	skillRows: SkillRow[],
	localPlayerUid: number | null,
	topValue: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

