
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async enableBlur() : Promise<void> {
    await TAURI_INVOKE("enable_blur");
},
async disableBlur() : Promise<void> {
    await TAURI_INVOKE("disable_blur");
},
async copySyncContainerData() : Promise<void> {
    await TAURI_INVOKE("copy_sync_container_data");
},
async getHeaderInfo() : Promise<Result<HeaderInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_header_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDpsPlayerWindow() : Promise<Result<PlayersWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dps_player_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDpsSkillWindow(playerUidStr: string) : Promise<Result<SkillsWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dps_skill_window", { playerUidStr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDpsBossOnlyPlayerWindow() : Promise<Result<PlayersWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dps_boss_only_player_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDpsBossOnlySkillWindow(playerUidStr: string) : Promise<Result<SkillsWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dps_boss_only_skill_window", { playerUidStr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHealPlayerWindow() : Promise<Result<PlayersWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_heal_player_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHealSkillWindow(playerUidStr: string) : Promise<Result<SkillsWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_heal_skill_window", { playerUidStr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: fetch player metadata (name, class, class_spec) from DB by UID
 */
async getPlayerMetadata(playerUid: number) : Promise<Result<PlayerMetadata | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_player_metadata", { playerUid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a player's metadata in the live encounter cache
 * This allows newly discovered player information (name, class, spec, ability_score) to be
 * reflected immediately in the live UI without waiting for the next full refresh
 * If the player entity doesn't exist yet, it will be created with the provided metadata.
 */
async updatePlayerMetadata(playerUid: number, name: string | null, playerClass: string | null, playerClassSpec: string | null, abilityScore: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_player_metadata", { playerUid, name, playerClass, playerClassSpec, abilityScore }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist player metadata to the database immediately
 * This ensures newly discovered metadata is saved even before encounter ends
 */
async persistPlayerMetadata(playerUid: number, name: string | null, playerClass: string | null, playerClassSpec: string | null, abilityScore: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("persist_player_metadata", { playerUid, name, playerClass, playerClassSpec, abilityScore }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the local player UID for the current encounter
 * This is needed to identify which player is "you" on the live meter
 * Normally this is set automatically when SyncToMeDeltaInfo packets arrive,
 * but this command allows explicit setting if needed
 */
async setLocalPlayerUid(playerUid: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_local_player_uid", { playerUid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current local player UID for the live encounter
 */
async getLocalPlayerUid() : Promise<number> {
    return await TAURI_INVOKE("get_local_player_uid");
},
async resetEncounter() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_encounter") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async togglePauseEncounter() : Promise<void> {
    await TAURI_INVOKE("toggle_pause_encounter");
},
async hardReset() : Promise<void> {
    await TAURI_INVOKE("hard_reset");
},
async getTestPlayerWindow() : Promise<PlayersWindow> {
    return await TAURI_INVOKE("get_test_player_window");
},
async getTestSkillWindow(playerUid: string) : Promise<Result<SkillsWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_test_skill_window", { playerUid }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllEncounterHistory() : Promise<Result<EncounterRecord[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_encounter_history") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEncounterDetail(encounterId: number) : Promise<Result<EncounterDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_encounter_detail", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteEncounterHistory(encounterId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_encounter_history", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAllData() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoricalPlayersWindow(encounterId: number) : Promise<Result<PlayersWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_historical_players_window", { encounterId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoricalSkillsWindow(encounterId: number, playerId: number) : Promise<Result<SkillsWindow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_historical_skills_window", { encounterId, playerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AbilityRecord = { id: number; player_id: number; skill_id: number; skill_name: string; total_damage: number; damage_hits: number; crit_value: number; crit_hits: number; lucky_value: number; lucky_hits: number }
export type EncounterDetail = { encounter: EncounterRecord; players: PlayerDetail[] }
export type EncounterRecord = { id: number; start_time: string; end_time: string; duration_ms: number; total_damage: number; total_healing: number }
export type HeaderInfo = { totalDps: number; totalDmg: number; elapsedMs: number; timeLastCombatPacketMs: number }
export type PlayerDetail = { player: PlayerRecord; abilities: AbilityRecord[] }
export type PlayerMetadata = { name: string; class: string | null; class_spec: string | null; ability_score: number | null }
export type PlayerRecord = { id: number; encounter_id: number; name: string; class: string | null; class_spec: string | null; ability_score: number | null; total_damage: number; damage_hits: number; crit_value: number; crit_hits: number; lucky_value: number; lucky_hits: number; total_healing: number; healing_hits: number }
export type PlayerRow = { uid: number; abilityScore: number; className: string; classSpecName: string; name: string; totalValue: number; valuePerSec: number; valuePct: number; critRate: number; critValueRate: number; luckyRate: number; luckyValueRate: number; hits: number; hitsPerMinute: number }
export type PlayersWindow = { playerRows: PlayerRow[]; localPlayerUid: number; topValue: number }
export type SkillRow = { uid: number; name: string; totalValue: number; valuePerSec: number; valuePct: number; critRate: number; critValueRate: number; luckyRate: number; luckyValueRate: number; hits: number; hitsPerMinute: number }
export type SkillsWindow = { inspectedPlayer: PlayerRow; skillRows: SkillRow[]; localPlayerUid: number; topValue: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
